staticDir = 'static'
baseURL = 'https://monitorpattern.github.io/dofreez/'
languageCode = 'fr-fr'
title = 'Zoé trébuche et Fred vacille'
#theme = 'hugo-story'
theme = 'ananke'
[params]
    custom_css = ['style.css']
